name: Snyk Security Scan

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Run Snyk Code to scan source code
      uses: snyk/actions/setup@master
      
    - name: Snyk Code test
      run: snyk code test --severity-threshold=high --sarif-file-output=snyk-code.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        
    - name: Upload Snyk Code results to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: snyk-code.sarif
        
    - name: Upload Snyk Code results as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: snyk-code-results
        path: snyk-code.sarif
